# Form implementation generated from reading ui file 'D:\python\Hocmay\Final_HocMay\ForgotPassword.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ForgotPassword(object):
    def setupUi(self, ForgotPassword):
        ForgotPassword.setObjectName("ForgotPassword")
        ForgotPassword.resize(1189, 788)
        ForgotPassword.setMaximumSize(QtCore.QSize(1189, 788))
        self.centralwidget = QtWidgets.QWidget(parent=ForgotPassword)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 1189, 751))
        self.label.setMaximumSize(QtCore.QSize(16777215, 751))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/Background.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 50, 351, 621))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet(" border-top-left-radius: 50px;     \n"
"    border-top-right-radius: 0px;    \n"
"    border-bottom-left-radius: 0px;    \n"
"    border-bottom-right-radius: 0px;  \n"
"\n"
"  ")
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_2.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/bgLogo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 50, 841, 621))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
" \n"
"    padding: 10px;\n"
" border: 1px solid #faf4ec; \n"
"border-top-left-radius: 50px;\n"
"border-top-right-radius: 0px;      /* góc trên phải */\n"
"    border-bottom-left-radius: 0px;    /* góc dưới trái */\n"
"    border-bottom-right-radius: 50px;  /* góc dưới phải */")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(570, 100, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(185, 110, 127);")
        self.label_3.setObjectName("label_3")
        self.lineEditPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPass.setGeometry(QtCore.QRect(590, 330, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditPass.setFont(font)
        self.lineEditPass.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPass.setObjectName("lineEditPass")
        self.pushButtonRegister = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRegister.setGeometry(QtCore.QRect(560, 590, 421, 41))
        self.pushButtonRegister.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonRegister.setFont(font)
        self.pushButtonRegister.setStyleSheet("color: rgb(104, 83, 92);\n"
"background-color: rgb(221, 160, 175);\n"
"border-radius: 15px;")
        self.pushButtonRegister.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditEmail.setGeometry(QtCore.QRect(590, 240, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditConfirmPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditConfirmPass.setGeometry(QtCore.QRect(590, 420, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditConfirmPass.setFont(font)
        self.lineEditConfirmPass.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditConfirmPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditConfirmPass.setObjectName("lineEditConfirmPass")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 250, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_email.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(550, 340, 31, 31))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_password.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(550, 420, 31, 41))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_confirmpass.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.lineEditOTP = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditOTP.setGeometry(QtCore.QRect(590, 510, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditOTP.setFont(font)
        self.lineEditOTP.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditOTP.setObjectName("lineEditOTP")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 520, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_otp.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEditPass.raise_()
        self.pushButtonRegister.raise_()
        self.lineEditEmail.raise_()
        self.lineEditConfirmPass.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.lineEditOTP.raise_()
        self.label_9.raise_()
        ForgotPassword.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ForgotPassword)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1189, 26))
        self.menubar.setObjectName("menubar")
        ForgotPassword.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ForgotPassword)
        self.statusbar.setObjectName("statusbar")
        ForgotPassword.setStatusBar(self.statusbar)

        self.retranslateUi(ForgotPassword)
        QtCore.QMetaObject.connectSlotsByName(ForgotPassword)

    def retranslateUi(self, ForgotPassword):
        _translate = QtCore.QCoreApplication.translate
        ForgotPassword.setWindowTitle(_translate("ForgotPassword", "MainWindow"))
        self.label_3.setText(_translate("ForgotPassword", "<html><head/><body><p align=\"center\">Reset password</p></body></html>"))
        self.lineEditPass.setText(_translate("ForgotPassword", "Password"))
        self.pushButtonRegister.setText(_translate("ForgotPassword", "Reset"))
        self.lineEditEmail.setText(_translate("ForgotPassword", "Email"))
        self.lineEditConfirmPass.setText(_translate("ForgotPassword", "Confirm Password"))
        self.lineEditOTP.setText(_translate("ForgotPassword", "OTP"))
