# Form implementation generated from reading ui file 'D:\python\Hocmay\Final_HocMay\UI\Login.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(1189, 788)
        Login.setMaximumSize(QtCore.QSize(1189, 16777215))
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 1191, 751))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\UI\\images/Background.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 50, 351, 621))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet(" border-top-left-radius: 50px;     \n"
"    border-top-right-radius: 0px;    \n"
"    border-bottom-left-radius: 0px;    \n"
"    border-bottom-right-radius: 0px;  \n"
"\n"
"  ")
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_2.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\UI\\images/bgLogo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 50, 841, 621))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
" \n"
"    padding: 10px;\n"
" border: 1px solid #faf4ec; \n"
"border-top-left-radius: 50px;\n"
"border-top-right-radius: 0px;      /* góc trên phải */\n"
"    border-bottom-left-radius: 0px;    /* góc dưới trái */\n"
"    border-bottom-right-radius: 50px;  /* góc dưới phải */")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 100, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(185, 110, 127);")
        self.label_3.setObjectName("label_3")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(590, 240, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditUserName.setFont(font)
        self.lineEditUserName.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.checkBoxSave = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxSave.setGeometry(QtCore.QRect(560, 420, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBoxSave.setFont(font)
        self.checkBoxSave.setStyleSheet("color: rgb(185, 110, 127);")
        self.checkBoxSave.setObjectName("checkBoxSave")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(560, 510, 421, 41))
        self.pushButtonLogin.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonLogin.setFont(font)
        self.pushButtonLogin.setStyleSheet("color: rgb(104, 83, 92);\n"
"background-color: rgb(221, 160, 175);\n"
"border-radius: 15px;")
        self.pushButtonLogin.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.labelForgot = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelForgot.setGeometry(QtCore.QRect(830, 420, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.labelForgot.setFont(font)
        self.labelForgot.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.labelForgot.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.labelForgot.setStyleSheet("color: rgb(185, 110, 127);")
        self.labelForgot.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.labelForgot.setObjectName("labelForgot")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(590, 350, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.pushButtonRegisterNow = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRegisterNow.setGeometry(QtCore.QRect(560, 590, 421, 41))
        self.pushButtonRegisterNow.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonRegisterNow.setFont(font)
        self.pushButtonRegisterNow.setStyleSheet("color: rgb(104, 83, 92);\n"
"background-color: rgb(221, 160, 175);\n"
"border-radius: 15px;")
        self.pushButtonRegisterNow.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonRegisterNow.setObjectName("pushButtonRegisterNow")
        self.labelForgotCus_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelForgotCus_2.setGeometry(QtCore.QRect(760, 560, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.labelForgotCus_2.setFont(font)
        self.labelForgotCus_2.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.labelForgotCus_2.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.labelForgotCus_2.setStyleSheet("color: rgb(185, 110, 127);")
        self.labelForgotCus_2.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.labelForgotCus_2.setObjectName("labelForgotCus_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(550, 250, 31, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\UI\\ic_username.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 360, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\UI\\images/ic_password.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEditUserName.raise_()
        self.checkBoxSave.raise_()
        self.pushButtonLogin.raise_()
        self.labelForgot.raise_()
        self.lineEditPassword.raise_()
        self.pushButtonRegisterNow.raise_()
        self.labelForgotCus_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        Login.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Login)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1189, 26))
        self.menubar.setObjectName("menubar")
        Login.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.label_3.setText(_translate("Login", "<html><head/><body><p align=\"center\">Log In</p></body></html>"))
        self.lineEditUserName.setText(_translate("Login", "UserName"))
        self.checkBoxSave.setText(_translate("Login", "Save the information"))
        self.pushButtonLogin.setText(_translate("Login", "Login"))
        self.labelForgot.setText(_translate("Login", "Forgot password?"))
        self.lineEditPassword.setText(_translate("Login", "Password"))
        self.pushButtonRegisterNow.setText(_translate("Login", "Register Now"))
        self.labelForgotCus_2.setText(_translate("Login", "Or"))
