# Form implementation generated from reading ui file 'D:\python\Hocmay\Final_HocMay\Register.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(1189, 788)
        Register.setMaximumSize(QtCore.QSize(1189, 788))
        self.centralwidget = QtWidgets.QWidget(parent=Register)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 1191, 751))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/Background.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 50, 351, 621))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet(" border-top-left-radius: 50px;     \n"
"    border-top-right-radius: 0px;    \n"
"    border-bottom-left-radius: 0px;    \n"
"    border-bottom-right-radius: 0px;  \n"
"\n"
"  ")
        self.label_2.setText("")
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_2.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/bgLogo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 50, 841, 621))
        self.label_4.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
" \n"
"    padding: 10px;\n"
" border: 1px solid #faf4ec; \n"
"border-top-left-radius: 50px;\n"
"border-top-right-radius: 0px;      /* góc trên phải */\n"
"    border-bottom-left-radius: 0px;    /* góc dưới trái */\n"
"    border-bottom-right-radius: 50px;  /* góc dưới phải */")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(670, 100, 211, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(185, 110, 127);")
        self.label_3.setObjectName("label_3")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(590, 220, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditUserName.setFont(font)
        self.lineEditUserName.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPass.setGeometry(QtCore.QRect(590, 400, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditPass.setFont(font)
        self.lineEditPass.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPass.setObjectName("lineEditPass")
        self.pushButtonRegister = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRegister.setGeometry(QtCore.QRect(560, 590, 421, 41))
        self.pushButtonRegister.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonRegister.setFont(font)
        self.pushButtonRegister.setStyleSheet("color: rgb(104, 83, 92);\n"
"background-color: rgb(221, 160, 175);\n"
"border-radius: 15px;")
        self.pushButtonRegister.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditEmail.setGeometry(QtCore.QRect(590, 310, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.lineEditConfirmPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditConfirmPass.setGeometry(QtCore.QRect(590, 490, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditConfirmPass.setFont(font)
        self.lineEditConfirmPass.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditConfirmPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditConfirmPass.setObjectName("lineEditConfirmPass")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(550, 230, 31, 31))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_username.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(550, 320, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_email.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.labelPassword = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelPassword.setGeometry(QtCore.QRect(550, 410, 31, 31))
        self.labelPassword.setText("")
        self.labelPassword.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_password.png"))
        self.labelPassword.setScaledContents(True)
        self.labelPassword.setObjectName("labelPassword")
        self.labelConfirmPassword = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelConfirmPassword.setGeometry(QtCore.QRect(550, 490, 31, 31))
        self.labelConfirmPassword.setText("")
        self.labelConfirmPassword.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_confirmpass.png"))
        self.labelConfirmPassword.setScaledContents(True)
        self.labelConfirmPassword.setObjectName("labelConfirmPassword")
        self.checkBoxTerm = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxTerm.setGeometry(QtCore.QRect(560, 550, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBoxTerm.setFont(font)
        self.checkBoxTerm.setStyleSheet("color: rgb(185, 110, 127);")
        self.checkBoxTerm.setObjectName("checkBoxTerm")
        self.label.raise_()
        self.label_4.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.lineEditUserName.raise_()
        self.lineEditPass.raise_()
        self.pushButtonRegister.raise_()
        self.lineEditEmail.raise_()
        self.lineEditConfirmPass.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.labelPassword.raise_()
        self.labelConfirmPassword.raise_()
        self.checkBoxTerm.raise_()
        Register.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Register)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1189, 26))
        self.menubar.setObjectName("menubar")
        Register.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Register)
        self.statusbar.setObjectName("statusbar")
        Register.setStatusBar(self.statusbar)

        self.retranslateUi(Register)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "MainWindow"))
        self.label_3.setText(_translate("Register", "<html><head/><body><p align=\"center\">Register</p></body></html>"))
        self.lineEditUserName.setText(_translate("Register", "UserName"))
        self.lineEditPass.setText(_translate("Register", "Password"))
        self.pushButtonRegister.setText(_translate("Register", "Register "))
        self.lineEditEmail.setText(_translate("Register", "Email"))
        self.lineEditConfirmPass.setText(_translate("Register", "Confirm Password"))
        self.checkBoxTerm.setText(_translate("Register", "By signing up you agree Terms and Conditions"))
