# Form implementation generated from reading ui file 'D:\python\Hocmay\Final_HocMay\ResetPassword.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ResetPassword(object):
    def setupUi(self, ResetPassword):
        ResetPassword.setObjectName("ResetPassword")
        ResetPassword.resize(1189, 788)
        self.centralwidget = QtWidgets.QWidget(parent=ResetPassword)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1189, 751))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 751))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/Background.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(180, 60, 841, 621))
        self.label_6.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
" \n"
"    padding: 10px;\n"
" border: 1px solid #faf4ec; \n"
"border-top-left-radius: 50px;\n"
"border-top-right-radius: 0px;      /* góc trên phải */\n"
"    border-bottom-left-radius: 0px;    /* góc dưới trái */\n"
"    border-bottom-right-radius: 50px;  /* góc dưới phải */")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(180, 60, 351, 621))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setStyleSheet(" border-top-left-radius: 50px;     \n"
"    border-top-right-radius: 0px;    \n"
"    border-bottom-left-radius: 0px;    \n"
"    border-bottom-right-radius: 0px;  \n"
"\n"
"  ")
        self.label_7.setText("")
        self.label_7.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_7.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/bgLogo.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(570, 130, 411, 81))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(185, 110, 127);")
        self.label_8.setObjectName("label_8")
        self.lineEditEmail_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditEmail_2.setGeometry(QtCore.QRect(590, 290, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditEmail_2.setFont(font)
        self.lineEditEmail_2.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditEmail_2.setObjectName("lineEditEmail_2")
        self.pushButtonRegister = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonRegister.setGeometry(QtCore.QRect(570, 490, 421, 41))
        self.pushButtonRegister.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semilight")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButtonRegister.setFont(font)
        self.pushButtonRegister.setStyleSheet("color: rgb(104, 83, 92);\n"
"background-color: rgb(221, 160, 175);\n"
"border-radius: 15px;")
        self.pushButtonRegister.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonRegister.setObjectName("pushButtonRegister")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(550, 300, 31, 31))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_password.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.lineEditEmail_3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditEmail_3.setGeometry(QtCore.QRect(590, 380, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditEmail_3.setFont(font)
        self.lineEditEmail_3.setStyleSheet("background-color: rgb(250, 244, 236);\n"
"    border: none;                                   /* Xóa viền mặc định */\n"
"    border-bottom:  2px solid rgba(104, 83, 92);\n"
"                         /* Màu chữ đen */\n"
"color: rgb(185, 110, 127);\n"
"    padding-bottom: 7px;                            /* Tạo khoảng cách giữa chữ và gạch */\n"
"")
        self.lineEditEmail_3.setObjectName("lineEditEmail_3")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(550, 380, 31, 41))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_confirmpass.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.label_11.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_home.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        ResetPassword.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ResetPassword)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1189, 26))
        self.menubar.setObjectName("menubar")
        ResetPassword.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ResetPassword)
        self.statusbar.setObjectName("statusbar")
        ResetPassword.setStatusBar(self.statusbar)

        self.retranslateUi(ResetPassword)
        QtCore.QMetaObject.connectSlotsByName(ResetPassword)

    def retranslateUi(self, ResetPassword):
        _translate = QtCore.QCoreApplication.translate
        ResetPassword.setWindowTitle(_translate("ResetPassword", "MainWindow"))
        self.label_8.setText(_translate("ResetPassword", "<html><head/><body><p align=\"center\">Reset Password</p></body></html>"))
        self.lineEditEmail_2.setText(_translate("ResetPassword", "New Password"))
        self.pushButtonRegister.setText(_translate("ResetPassword", "Reset"))
        self.lineEditEmail_3.setText(_translate("ResetPassword", "Confirm New Password"))
