# Form implementation generated from reading ui file 'D:\python\Hocmay\Final_HocMay\CustomerManagement.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CustomerManagement(object):
    def setupUi(self, CustomerManagement):
        CustomerManagement.setObjectName("CustomerManagement")
        CustomerManagement.resize(1189, 788)
        self.centralwidget = QtWidgets.QWidget(parent=CustomerManagement)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1191, 751))
        self.label.setStyleSheet("border-image: url(:/Background/Background.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/Background.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1100, 10, 81, 71))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.labelHome = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelHome.setGeometry(QtCore.QRect(20, 10, 31, 31))
        self.labelHome.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.labelHome.setText("")
        self.labelHome.setPixmap(QtGui.QPixmap("D:\\python\\Hocmay\\Final_HocMay\\images/ic_home.png"))
        self.labelHome.setScaledContents(True)
        self.labelHome.setObjectName("labelHome")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 30, 661, 81))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color: rgba(255, 255, 255, 192);\n"
"    padding: 10px;\n"
" border: 1px solid #faf4ec; \n"
"border-top-left-radius: 30px;\n"
"border-top-right-radius: 30px;    \n"
"    border-bottom-left-radius: 30px;   \n"
"    border-bottom-right-radius: 30px; \n"
"color: rgb(185, 110, 127);")
        self.label_5.setObjectName("label_5")
        self.tableWidgetCustomer = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetCustomer.setGeometry(QtCore.QRect(120, 140, 951, 301))
        self.tableWidgetCustomer.setStyleSheet("color: rgb(185, 110, 127);\n"
"background-color: rgb(250, 244, 236);\n"
"")
        self.tableWidgetCustomer.setObjectName("tableWidgetCustomer")
        self.tableWidgetCustomer.setColumnCount(3)
        self.tableWidgetCustomer.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCustomer.setHorizontalHeaderItem(2, item)
        self.groupBoxDetail = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxDetail.setGeometry(QtCore.QRect(120, 450, 951, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBoxDetail.setFont(font)
        self.groupBoxDetail.setStyleSheet("background-color: rgb(232, 221, 222);\n"
"color: rgb(185, 110, 127);")
        self.groupBoxDetail.setObjectName("groupBoxDetail")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBoxDetail)
        self.label_4.setGeometry(QtCore.QRect(30, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBoxDetail)
        self.label_6.setGeometry(QtCore.QRect(30, 110, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBoxDetail)
        self.label_7.setGeometry(QtCore.QRect(460, 40, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.groupBoxDetail)
        self.lineEditUserName.setGeometry(QtCore.QRect(120, 40, 231, 31))
        self.lineEditUserName.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;    \n"
"    border-bottom-left-radius: 10px;   \n"
"    border-bottom-right-radius: 10px; ")
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.groupBoxDetail)
        self.lineEditPassword.setGeometry(QtCore.QRect(550, 40, 231, 31))
        self.lineEditPassword.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;    \n"
"    border-bottom-left-radius: 10px;   \n"
"    border-bottom-right-radius: 10px; ")
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.groupBoxDetail)
        self.lineEditEmail.setGeometry(QtCore.QRect(120, 110, 311, 31))
        self.lineEditEmail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;    \n"
"    border-bottom-left-radius: 10px;   \n"
"    border-bottom-right-radius: 10px; ")
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.pushButtonNew = QtWidgets.QPushButton(parent=self.groupBoxDetail)
        self.pushButtonNew.setGeometry(QtCore.QRect(90, 180, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonNew.setFont(font)
        self.pushButtonNew.setStyleSheet("background-color: rgb(185, 110, 127);\n"
"color: rgb(232, 221, 222);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;    \n"
"    border-bottom-left-radius: 10px;   \n"
"    border-bottom-right-radius: 10px; ")
        self.pushButtonNew.setObjectName("pushButtonNew")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.groupBoxDetail)
        self.pushButtonSave.setGeometry(QtCore.QRect(320, 180, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setStyleSheet("background-color: rgb(185, 110, 127);\n"
"color: rgb(232, 221, 222);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;    \n"
"    border-bottom-left-radius: 10px;   \n"
"    border-bottom-right-radius: 10px; ")
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonClear = QtWidgets.QPushButton(parent=self.groupBoxDetail)
        self.pushButtonClear.setGeometry(QtCore.QRect(550, 180, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setStyleSheet("background-color: rgb(185, 110, 127);\n"
"color: rgb(232, 221, 222);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;    \n"
"    border-bottom-left-radius: 10px;   \n"
"    border-bottom-right-radius: 10px; ")
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.groupBoxDetail)
        self.pushButtonDelete.setGeometry(QtCore.QRect(760, 180, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonDelete.setFont(font)
        self.pushButtonDelete.setStyleSheet("background-color: rgb(185, 110, 127);\n"
"color: rgb(232, 221, 222);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;    \n"
"    border-bottom-left-radius: 10px;   \n"
"    border-bottom-right-radius: 10px; ")
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        CustomerManagement.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=CustomerManagement)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1189, 26))
        self.menubar.setObjectName("menubar")
        CustomerManagement.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=CustomerManagement)
        self.statusbar.setObjectName("statusbar")
        CustomerManagement.setStatusBar(self.statusbar)

        self.retranslateUi(CustomerManagement)
        QtCore.QMetaObject.connectSlotsByName(CustomerManagement)

    def retranslateUi(self, CustomerManagement):
        _translate = QtCore.QCoreApplication.translate
        CustomerManagement.setWindowTitle(_translate("CustomerManagement", "MainWindow"))
        self.label_5.setText(_translate("CustomerManagement", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600;\">CUSTOMER MANAGEMENT</span></p></body></html>"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(0)
        item.setText(_translate("CustomerManagement", "UserName"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(1)
        item.setText(_translate("CustomerManagement", "Email"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(2)
        item.setText(_translate("CustomerManagement", "Password"))
        self.groupBoxDetail.setTitle(_translate("CustomerManagement", "Detail"))
        self.label_4.setText(_translate("CustomerManagement", "UserName"))
        self.label_6.setText(_translate("CustomerManagement", "Email"))
        self.label_7.setText(_translate("CustomerManagement", "Password"))
        self.pushButtonNew.setText(_translate("CustomerManagement", "New"))
        self.pushButtonSave.setText(_translate("CustomerManagement", "Save"))
        self.pushButtonClear.setText(_translate("CustomerManagement", "Clear"))
        self.pushButtonDelete.setText(_translate("CustomerManagement", "Delete"))
